version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  commit-message:
    prefix: "ci(github-actions)"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: "daily"
  reviewers:
  - "SAP/ui5-foundation"
  versioning-strategy: increase
  commit-message:
    prefix: "deps"
    prefix-development: "build(deps-dev)"
  ignore:
    - dependency-name: "@types/node" # Should be manually kept in sync with the minimum supported Node.js version
    - dependency-name: "@sapui5/types" # Major/minor updates should be done manually
      # Only perform patch updates (i.e. ignore major/minor updates)
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
