version = 1
SPDX-PackageName = "ui5-linter"
SPDX-PackageSupplier = "SAP OpenUI5 <openui5@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/SAP/ui5-linter"
SPDX-PackageComment = "The code in this project may include calls to APIs (“API Calls”) of\n SAP or third-party products or services developed outside of this project\n (“External Products”).\n “APIs” means application programming interfaces, as well as their respective\n specifications and implementing code that allows software to communicate with\n other software.\n API Calls to External Products are not licensed under the open source license\n that governs this project. The use of such API Calls and related External\n Products are subject to applicable additional agreements with the relevant\n provider of the External Products. In no event shall the open source license\n that governs this project grant any rights in or to any External Products,or\n alter, expand or supersede any terms of the applicable additional agreements.\n If you have a valid license agreement with SAP for the use of a particular SAP\n External Product, then you may make use of any API Calls included in this\n project’s code for that SAP External Product, subject to the terms of such\n license agreement. If you do not have a valid license agreement for the use of\n a particular SAP External Product, then you may only make use of any API Calls\n in this project for that SAP External Product for your internal, non-productive\n and non-commercial test and evaluation of such API Calls. Nothing herein grants\n you any rights to use or access any SAP External Product, or provide any third\n parties the right to use of access any SAP External Product, through API Calls."

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 SAP SE or an SAP affiliate company and UI5 linter contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "src/linter/xmlTemplate/lib/EventHandlerResolver.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "2009-2025 SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileComment = "This file is a copy of sap/ui/core/mvc/EventHandlerResolver.js from the OpenUI5 project."

[[annotations]]
path = "src/linter/xmlTemplate/lib/JSTokenizer.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "2009-2024 SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileComment = "This file is a copy of sap/base/util/JSTokenizer.js from the OpenUI5 project."

[[annotations]]
path = "src/linter/binding/lib/BindingParser.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "2009-2025 SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileComment = "This file is a copy of sap/ui/base/BindingParser.js from the OpenUI5 project."

[[annotations]]
path = "src/linter/binding/lib/ExpressionParser.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "2009-2025 SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileComment = "This file is a copy of sap/ui/base/ExpressionParser.js from the OpenUI5 project."

[[annotations]]
path = "src/linter/binding/lib/BindingMode.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "2009-2025 SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileComment = "This file is a copy of sap/ui/model/BindingMode.js from the OpenUI5 project."

[[annotations]]
path = "src/linter/binding/lib/util/deepEqual.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "2009-2025 SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileComment = "This file is a copy of sap/base/util/deepEqual.js from the OpenUI5 project."

[[annotations]]
path = "src/linter/binding/lib/strings/escapeRegExp.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "2009-2025 SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileComment = "This file is a copy of sap/base/strings/escapeRegExp.js from the OpenUI5 project."

[[annotations]]
path = "src/formatter/lib/resolveLinks.ts"
precedence = "aggregate"
SPDX-FileCopyrightText = "2009-2024 SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileComment = "This file contains parts of the https://github.com/SAP/ui5-builder file lib/processors/jsdoc/lib/transformApiJson.cjs which itself is a copy from the OpenUI5 file lib/jsdoc/transformApiJson.js."

[[annotations]]
path = "src/manifest.d.ts"
precedence = "aggregate"
SPDX-FileCopyrightText = "2009-2020 SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileComment = "TypeScript definitions created from https://github.com/SAP/ui5-manifest/tree/v1.60.0"

[[annotations]]
path = "test/fixtures/transpiler/amd/sapUiTestGenericUtils.js"
precedence = "aggregate"
SPDX-FileCopyrightText = "2009-2024 SAP SE or an SAP affiliate company"
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileComment = "This file is a copy of sap/ui/test/generic/Utils.js from the OpenUI5 project."

[[annotations]]
path = "scripts/metadataProvider/model.ts"
precedence = "aggregate"
SPDX-FileCopyrightText = "2020-2021 SAP SE or an SAP affiliate company and UI5 Language Assistant contributors"
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileComment = "This file contains a part from the https://github.com/SAP/ui5-language-assistant project (getTypeNameFix)."
