// This file is generated by the createTypes script.

declare module "sap/tnt/NavigationListItemDesign" {
	import {NavigationListItemDesign} from "sap/tnt/library";

	/**
	 * Available types for navigation list item.
	 * 
	 * This enum is part of the 'sap/tnt/library' module export and must be accessed by the property 'NavigationListItemDesign'.
	 *
	 * @experimental - Behavior might change.
	 * @public
	 * @since 1.133.0
	*/
	export default NavigationListItemDesign;
}

declare module "sap/tnt/RenderMode" {
	import {RenderMode} from "sap/tnt/library";

	/**
	 * Predefined types of <code>InfoLabel</code>
	 * 
	 * This enum is part of the 'sap/tnt/library' module export and must be accessed by the property 'RenderMode'.
	 *
	 * @public
	*/
	export default RenderMode;
}

declare module "sap/tnt/SideNavigationDesign" {
	import {SideNavigationDesign} from "sap/tnt/library";

	/**
	 * Available options for the Side Navigation design.
	 * 
	 * This enum is part of the 'sap/tnt/library' module export and must be accessed by the property 'SideNavigationDesign'.
	 *
	 * @experimental - Behavior might change.
	 * @public
	 * @since 1.134.0
	*/
	export default SideNavigationDesign;
}
