// This file is generated by the createTypes script.

declare module "sap/viz/ui5/types/Area_drawingEffect" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Area_drawingEffect
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Area_drawingEffect'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Area_drawingEffect;
}

declare module "sap/viz/ui5/types/Area_marker_shape" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Area_marker_shape
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Area_marker_shape'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Area_marker_shape;
}

declare module "sap/viz/ui5/types/Area_mode" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Area_mode
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Area_mode'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Area_mode;
}

declare module "sap/viz/ui5/types/Area_orientation" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Area_orientation
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Area_orientation'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Area_orientation;
}

declare module "sap/viz/ui5/types/Axis_gridline_type" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Axis_gridline_type
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Axis_gridline_type'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Axis_gridline_type;
}

declare module "sap/viz/ui5/types/Axis_label_unitFormatType" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Axis_label_unitFormatType
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Axis_label_unitFormatType'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Axis_label_unitFormatType;
}

declare module "sap/viz/ui5/types/Axis_position" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Axis_position
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Axis_position'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Axis_position;
}

declare module "sap/viz/ui5/types/Axis_type" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Axis_type
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Axis_type'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Axis_type;
}

declare module "sap/viz/ui5/types/Background_direction" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Background_direction
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Background_direction'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Background_direction;
}

declare module "sap/viz/ui5/types/Background_drawingEffect" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Background_drawingEffect
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Background_drawingEffect'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Background_drawingEffect;
}

declare module "sap/viz/ui5/types/Bar_drawingEffect" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Bar_drawingEffect
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Bar_drawingEffect'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Bar_drawingEffect;
}

declare module "sap/viz/ui5/types/Bar_orientation" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Bar_orientation
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Bar_orientation'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Bar_orientation;
}

declare module "sap/viz/ui5/types/Bubble_drawingEffect" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Bubble_drawingEffect
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Bubble_drawingEffect'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Bubble_drawingEffect;
}

declare module "sap/viz/ui5/types/Bullet_drawingEffect" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Bullet_drawingEffect
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Bullet_drawingEffect'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Bullet_drawingEffect;
}

declare module "sap/viz/ui5/types/Bullet_orientation" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Bullet_orientation
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Bullet_orientation'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Bullet_orientation;
}

declare module "sap/viz/ui5/types/Combination_drawingEffect" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Combination_drawingEffect
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Combination_drawingEffect'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Combination_drawingEffect;
}

declare module "sap/viz/ui5/types/Combination_orientation" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Combination_orientation
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Combination_orientation'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Combination_orientation;
}

declare module "sap/viz/ui5/types/controller/Interaction_pan_orientation" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.controller.Interaction_pan_orientation
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.controller.Interaction_pan_orientation'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.controller.Interaction_pan_orientation;
}

declare module "sap/viz/ui5/types/controller/Interaction_selectability_mode" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.controller.Interaction_selectability_mode
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.controller.Interaction_selectability_mode'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.controller.Interaction_selectability_mode;
}

declare module "sap/viz/ui5/types/Datalabel_orientation" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Datalabel_orientation
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Datalabel_orientation'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Datalabel_orientation;
}

declare module "sap/viz/ui5/types/Datalabel_outsidePosition" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Datalabel_outsidePosition
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Datalabel_outsidePosition'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Datalabel_outsidePosition;
}

declare module "sap/viz/ui5/types/Datalabel_paintingMode" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Datalabel_paintingMode
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Datalabel_paintingMode'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Datalabel_paintingMode;
}

declare module "sap/viz/ui5/types/Datalabel_position" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Datalabel_position
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Datalabel_position'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Datalabel_position;
}

declare module "sap/viz/ui5/types/legend/Common_alignment" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.legend.Common_alignment
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.legend.Common_alignment'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.legend.Common_alignment;
}

declare module "sap/viz/ui5/types/legend/Common_drawingEffect" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.legend.Common_drawingEffect
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.legend.Common_drawingEffect'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.legend.Common_drawingEffect;
}

declare module "sap/viz/ui5/types/legend/Common_position" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.legend.Common_position
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.legend.Common_position'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.legend.Common_position;
}

declare module "sap/viz/ui5/types/legend/Common_type" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.legend.Common_type
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.legend.Common_type'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.legend.Common_type;
}

declare module "sap/viz/ui5/types/Legend_layout_position" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Legend_layout_position
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Legend_layout_position'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Legend_layout_position;
}

declare module "sap/viz/ui5/types/Line_drawingEffect" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Line_drawingEffect
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Line_drawingEffect'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Line_drawingEffect;
}

declare module "sap/viz/ui5/types/Line_marker_shape" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Line_marker_shape
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Line_marker_shape'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Line_marker_shape;
}

declare module "sap/viz/ui5/types/Line_orientation" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Line_orientation
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Line_orientation'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Line_orientation;
}

declare module "sap/viz/ui5/types/Pie_drawingEffect" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Pie_drawingEffect
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Pie_drawingEffect'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Pie_drawingEffect;
}

declare module "sap/viz/ui5/types/Pie_valign" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Pie_valign
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Pie_valign'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Pie_valign;
}

declare module "sap/viz/ui5/types/Scatter_drawingEffect" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Scatter_drawingEffect
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Scatter_drawingEffect'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Scatter_drawingEffect;
}

declare module "sap/viz/ui5/types/StackedVerticalBar_drawingEffect" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.StackedVerticalBar_drawingEffect
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.StackedVerticalBar_drawingEffect'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.StackedVerticalBar_drawingEffect;
}

declare module "sap/viz/ui5/types/StackedVerticalBar_mode" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.StackedVerticalBar_mode
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.StackedVerticalBar_mode'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.StackedVerticalBar_mode;
}

declare module "sap/viz/ui5/types/StackedVerticalBar_orientation" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.StackedVerticalBar_orientation
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.StackedVerticalBar_orientation'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.StackedVerticalBar_orientation;
}

declare module "sap/viz/ui5/types/Title_alignment" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Title_alignment
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Title_alignment'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Title_alignment;
}

declare module "sap/viz/ui5/types/Tooltip_drawingEffect" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.Tooltip_drawingEffect
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.Tooltip_drawingEffect'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.Tooltip_drawingEffect;
}

declare module "sap/viz/ui5/types/VerticalBar_drawingEffect" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.VerticalBar_drawingEffect
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.VerticalBar_drawingEffect'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.VerticalBar_drawingEffect;
}

declare module "sap/viz/ui5/types/VerticalBar_orientation" {
	import {ui5} from "sap/viz/library";

	/**
	 * List (Enum) type sap.viz.ui5.types.VerticalBar_orientation
	 * 
	 * This enum is part of the 'sap/viz/library' module export and must be accessed by the property 'ui5.types.VerticalBar_orientation'.
	 *
	 * @experimental (since 1.7.2) - Charting API is not finished yet and might change completely.
	 * @deprecated (since 1.32.0) - The chart controls in the <code>sap.viz.ui5</code> package (which were always marked as <i>experimental</i>) have been deprecated since 1.32.0. They are no longer actively developed and won't receive new features or improvements, only important bug fixes. They will only remain in the SAPUI5 distribution for backward compatibility.

<b>SAP strongly recommends that existing consumers of those controls migrate to the new {@link sap.viz.ui5.controls.VizFrame VizFrame} control to benefit from new charting enhancements and timely support. </b>

<b>Note</b>: As the feature set, design and API usage of VizFrame might differ from the old chart controls, make sure you evaluate it thoroughly before migration.
	 * @public
	 * @since 1.7.2
	*/
	export default ui5.types.VerticalBar_orientation;
}
