// This file is generated by the createTypes script.

declare module "sap/ui/export/EdmType" {
	import {EdmType} from "sap/ui/export/library";

	/**
	 * EDM data types for document export.
	 * 
	 * This enum is part of the 'sap/ui/export/library' module export and must be accessed by the property 'EdmType'.
	 *
	 * @public
	 * @since 1.50.0
	*/
	export default EdmType;
}

declare module "sap/ui/export/FileType" {
	import {FileType} from "sap/ui/export/library";

	/**
	 * File types for document export.
	 * 
	 * This enum is part of the 'sap/ui/export/library' module export and must be accessed by the property 'FileType'.
	 *
	 * @public
	 * @since 1.78
	*/
	export default FileType;
}
