// This file is generated by the createTypes script.

declare module "sap/makit/ChartType" {
	import {ChartType} from "sap/makit/library";

	/**
	 * Enumeration for chart type
	 * 
	 * This enum is part of the 'sap/makit/library' module export and must be accessed by the property 'ChartType'.
	 *
	 * @deprecated (since 1.38) - MAKIT charts have been replaced with sap.viz and vizFrame in 1.38. This control will not be supported anymore from 1.38.
	 * @public
	 * @since 1.8
	*/
	export default ChartType;
}

declare module "sap/makit/LegendPosition" {
	import {LegendPosition} from "sap/makit/library";

	/**
	 * Enumeration for legend position.
	 * 
	 * This enum is part of the 'sap/makit/library' module export and must be accessed by the property 'LegendPosition'.
	 *
	 * @deprecated (since 1.38) - MAKIT charts have been replaced with sap.viz and vizFrame in 1.38. This control will not be supported anymore from 1.38.
	 * @public
	*/
	export default LegendPosition;
}

declare module "sap/makit/SortOrder" {
	import {SortOrder} from "sap/makit/library";

	/**
	 * Enumeration for sort order
	 * 
	 * This enum is part of the 'sap/makit/library' module export and must be accessed by the property 'SortOrder'.
	 *
	 * @deprecated (since 1.38) - MAKIT charts have been replaced with sap.viz and vizFrame in 1.38. This control will not be supported anymore from 1.38.
	 * @public
	 * @since 1.8
	*/
	export default SortOrder;
}

declare module "sap/makit/ValueBubblePosition" {
	import {ValueBubblePosition} from "sap/makit/library";

	/**
	 * Position for Value Bubble only applies to Pie/Donut Chart.
	 * 
	 * This enum is part of the 'sap/makit/library' module export and must be accessed by the property 'ValueBubblePosition'.
	 *
	 * @deprecated (since 1.38) - MAKIT charts have been replaced with sap.viz and vizFrame in 1.38. This control will not be supported anymore from 1.38.
	 * @public
	 * @since 1.8
	*/
	export default ValueBubblePosition;
}

declare module "sap/makit/ValueBubbleStyle" {
	import {ValueBubbleStyle} from "sap/makit/library";

	/**
	 * Enumeration for Value Bubble's positioning style. This applies all chart types except Pie/Donut/HBar chart.
	 * 
	 * This enum is part of the 'sap/makit/library' module export and must be accessed by the property 'ValueBubbleStyle'.
	 *
	 * @deprecated (since 1.38) - MAKIT charts have been replaced with sap.viz and vizFrame in 1.38. This control will not be supported anymore from 1.38.
	 * @public
	 * @since 1.8
	*/
	export default ValueBubbleStyle;
}
