// This file is generated by the createTypes script.

declare module "sap/ui/suite/TaskCircleColor" {
	import {TaskCircleColor} from "sap/ui/suite/library";

	/**
	 * Defined color values for the Task Circle Control
	 * 
	 * This enum is part of the 'sap/ui/suite/library' module export and must be accessed by the property 'TaskCircleColor'.
	 *
	 * @public
	*/
	export default TaskCircleColor;
}
