// This file is generated by the createTypes script.

declare module "sap/me/CalendarDesign" {
	import {CalendarDesign} from "sap/me/library";

	/**
	 * Type of Design for the Calendar
	 * 
	 * This enum is part of the 'sap/me/library' module export and must be accessed by the property 'CalendarDesign'.
	 *
	 * @experimental (since 1.12) - API is not yet finished and might change completely
	 * @deprecated (since 1.34)
	 * @public
	*/
	export default CalendarDesign;
}

declare module "sap/me/CalendarEventType" {
	import {CalendarEventType} from "sap/me/library";

	/**
	 * Type code for a calendar event
	 * 
	 * This enum is part of the 'sap/me/library' module export and must be accessed by the property 'CalendarEventType'.
	 *
	 * @experimental (since 1.12) - API is not yet finished and might change completely
	 * @deprecated (since 1.34)
	 * @public
	*/
	export default CalendarEventType;
}

declare module "sap/me/CalendarSelectionMode" {
	import {CalendarSelectionMode} from "sap/me/library";

	/**
	 * Selection Mode for the Calendar
	 * 
	 * This enum is part of the 'sap/me/library' module export and must be accessed by the property 'CalendarSelectionMode'.
	 *
	 * @experimental (since 1.12) - API is not yet finished and might change completely
	 * @deprecated (since 1.34)
	 * @public
	*/
	export default CalendarSelectionMode;
}
