// This file is generated by the createTypes script.

declare module "sap/ui/richtexteditor/EditorType" {
	import {EditorType} from "sap/ui/richtexteditor/library";

	/**
	 * Determines which editor component should be used for editing the text.
	 * 
	 * This enum is part of the 'sap/ui/richtexteditor/library' module export and must be accessed by the property 'EditorType'.
	 *
	 * @public
	*/
	export default EditorType;
}
