// This file is generated by the createTypes script.

declare module "sap/suite/ui/generic/template/displayMode" {
	import {displayMode} from "sap/suite/ui/generic/template/library";

	/**
	 * A static enumeration type which indicates the mode of targeted page while using navigateInternal extensionAPI
	 * 
	 * This enum is part of the 'sap/suite/ui/generic/template/library' module export and must be accessed by the property 'displayMode'.
	 *
	 * @public
	*/
	export default displayMode;
}
