// This file is generated by the createTypes script.

declare module "sap/tnt/RenderMode" {
	import {RenderMode} from "sap/tnt/library";

	/**
	 * Predefined types of <code>InfoLabel</code>
	 *
	 * @public
	*/
	export default RenderMode;
}
