// This file is generated by the createTypes script.

declare module "sap/ui/support/Audiences" {
	import {Audiences} from "sap/ui/support/library";

	/**
	 * Defines the Audiences.
	 * 
	 * This enum is part of the 'sap/ui/support/library' module export and must be accessed by the property 'Audiences'.
	 *
	 * @public
	 * @since 1.50
	*/
	export default Audiences;
}

declare module "sap/ui/support/Categories" {
	import {Categories} from "sap/ui/support/library";

	/**
	 * Issue Categories.
	 * 
	 * This enum is part of the 'sap/ui/support/library' module export and must be accessed by the property 'Categories'.
	 *
	 * @public
	 * @since 1.50
	*/
	export default Categories;
}

declare module "sap/ui/support/HistoryFormats" {
	import {HistoryFormats} from "sap/ui/support/library";

	/**
	 * Analysis history formats.
	 * 
	 * This enum is part of the 'sap/ui/support/library' module export and must be accessed by the property 'HistoryFormats'.
	 *
	 * @public
	 * @since 1.58
	*/
	export default HistoryFormats;
}

declare module "sap/ui/support/Severity" {
	import {Severity} from "sap/ui/support/library";

	/**
	 * Defines severity types.
	 * 
	 * This enum is part of the 'sap/ui/support/library' module export and must be accessed by the property 'Severity'.
	 *
	 * @public
	 * @since 1.50
	*/
	export default Severity;
}

declare module "sap/ui/support/SystemPresets" {
	import {SystemPresets} from "sap/ui/support/library";

	/**
	 * Contains the available system presets.
	 * 
	 * This enum is part of the 'sap/ui/support/library' module export and must be accessed by the property 'SystemPresets'.
	 *
	 * @public
	 * @since 1.60
	*/
	export default SystemPresets;
}
