// This file is generated by the createTypes script.

declare module "sap/ca/ui/charts/ChartColor" {
	import {charts} from "sap/ca/ui/library";

	/**
	 * Enumeration of available color to be used in sap.ca.ui charts.
	 * 
	 * This enum is part of the 'sap/ca/ui/library' module export and must be accessed by the property 'charts.ChartColor'.
	 *
	 * @deprecated (since 1.24) - Sap.ca charts have been replaced with sap.viz and VizFrame in 1.24. The UI5 control "sap.viz.ui5.controls.VizFrame" serves as a single point of entry for all the new charts. Now that 1.24 is available you are asked to use sap.viz charts and the VizFrame instead! This control will not be supported anymore from 1.24.
	 * @public
	*/
	export default charts.ChartColor;
}

declare module "sap/ca/ui/charts/ChartSelectionMode" {
	import {charts} from "sap/ca/ui/library";

	/**
	 * Determines the selection mode of a Chart.
	 * 
	 * This enum is part of the 'sap/ca/ui/library' module export and must be accessed by the property 'charts.ChartSelectionMode'.
	 *
	 * @deprecated (since 1.24) - Sap.ca charts have been replaced with sap.viz and VizFrame in 1.24. The UI5 control "sap.viz.ui5.controls.VizFrame" serves as a single point of entry for all the new charts. Now that 1.24 is available you are asked to use sap.viz charts and the VizFrame instead! This control will not be supported anymore from 1.24.
	 * @public
	*/
	export default charts.ChartSelectionMode;
}

declare module "sap/ca/ui/charts/ChartSemanticColor" {
	import {charts} from "sap/ca/ui/library";

	/**
	 * Enumeration of available semantic color to be used in sap.Ca.ui
	 * 
	 * This enum is part of the 'sap/ca/ui/library' module export and must be accessed by the property 'charts.ChartSemanticColor'.
	 *
	 * @deprecated (since 1.24) - Sap.ca charts have been replaced with sap.viz and VizFrame in 1.24. The UI5 control "sap.viz.ui5.controls.VizFrame" serves as a single point of entry for all the new charts. Now that 1.24 is available you are asked to use sap.viz charts and the VizFrame instead! This control will not be supported anymore from 1.24.
	 * @public
	*/
	export default charts.ChartSemanticColor;
}
