// This file is generated by the createTypes script.

declare module "sap/ui/unified/CalendarAppointmentHeight" {
	import {CalendarAppointmentHeight} from "sap/ui/unified/library";

	/**
	 * Types of a calendar appointment display mode
	 * 
	 * This enum is part of the 'sap/ui/unified/library' module export and must be accessed by the property 'CalendarAppointmentHeight'.
	 *
	 * @public
	 * @since 1.80.0
	*/
	export default CalendarAppointmentHeight;
}

declare module "sap/ui/unified/CalendarAppointmentRoundWidth" {
	import {CalendarAppointmentRoundWidth} from "sap/ui/unified/library";

	/**
	 * Types of a calendar appointment display mode
	 * 
	 * This enum is part of the 'sap/ui/unified/library' module export and must be accessed by the property 'CalendarAppointmentRoundWidth'.
	 *
	 * @experimental (since 1.81.0)
	 * @public
	 * @since 1.81.0
	*/
	export default CalendarAppointmentRoundWidth;
}

declare module "sap/ui/unified/CalendarAppointmentVisualization" {
	import {CalendarAppointmentVisualization} from "sap/ui/unified/library";

	/**
	 * Visualization types for {@link sap.ui.unified.CalendarAppointment}.
	 * 
	 * This enum is part of the 'sap/ui/unified/library' module export and must be accessed by the property 'CalendarAppointmentVisualization'.
	 *
	 * @public
	 * @since 1.40.0
	*/
	export default CalendarAppointmentVisualization;
}

declare module "sap/ui/unified/CalendarDayType" {
	import {CalendarDayType} from "sap/ui/unified/library";

	/**
	 * Types of a calendar day used for visualization.
	 * 
	 * This enum is part of the 'sap/ui/unified/library' module export and must be accessed by the property 'CalendarDayType'.
	 *
	 * @public
	 * @since 1.13
	*/
	export default CalendarDayType;
}

declare module "sap/ui/unified/CalendarIntervalType" {
	import {CalendarIntervalType} from "sap/ui/unified/library";

	/**
	 * Interval types in a <code>CalendarRow</code>.
	 * 
	 * This enum is part of the 'sap/ui/unified/library' module export and must be accessed by the property 'CalendarIntervalType'.
	 *
	 * @public
	 * @since 1.34.0
	*/
	export default CalendarIntervalType;
}

declare module "sap/ui/unified/ColorPickerMode" {
	import {ColorPickerMode} from "sap/ui/unified/library";

	/**
	 * different styles for a ColorPicker.
	 * 
	 * This enum is part of the 'sap/ui/unified/library' module export and must be accessed by the property 'ColorPickerMode'.
	 *
	 * @public
	*/
	export default ColorPickerMode;
}

declare module "sap/ui/unified/ContentSwitcherAnimation" {
	import {ContentSwitcherAnimation} from "sap/ui/unified/library";

	/**
	 * Predefined animations for the ContentSwitcher
	 * 
	 * This enum is part of the 'sap/ui/unified/library' module export and must be accessed by the property 'ContentSwitcherAnimation'.
	 *
	 * @experimental (since 1.16.0) - API is not yet finished and might change completely
	 * @public
	 * @since 1.16.0
	*/
	export default ContentSwitcherAnimation;
}

declare module "sap/ui/unified/GroupAppointmentsMode" {
	import {GroupAppointmentsMode} from "sap/ui/unified/library";

	/**
	 * Types of display mode for overlapping appointments.
	 * 
	 * This enum is part of the 'sap/ui/unified/library' module export and must be accessed by the property 'GroupAppointmentsMode'.
	 *
	 * @public
	 * @since 1.48.0
	*/
	export default GroupAppointmentsMode;
}

declare module "sap/ui/unified/RecurrenceType" {
	import {RecurrenceType} from "sap/ui/unified/library";

	/**
	 * Interval types in a <code>RecurrenceType</code>.
	 * 
	 * This enum is part of the 'sap/ui/unified/library' module export and must be accessed by the property 'RecurrenceType'.
	 *
	 * @public
	 * @since 1.127.0
	*/
	export default RecurrenceType;
}

declare module "sap/ui/unified/StandardCalendarLegendItem" {
	import {StandardCalendarLegendItem} from "sap/ui/unified/library";

	/**
	 * Standard day types visualized in a {@link sap.m.PlanningCalendarLegend}, which correspond to days in a {@link sap.ui.unified.Calendar}.
	 * 
	 * This enum is part of the 'sap/ui/unified/library' module export and must be accessed by the property 'StandardCalendarLegendItem'.
	 *
	 * @public
	 * @since 1.50
	*/
	export default StandardCalendarLegendItem;
}
