// This file is generated by the createTypes script.

declare module "sap/ui/webc/fiori/BarDesign" {
	import {BarDesign} from "sap/ui/webc/fiori/library";

	/**
	 * Different types of Bar design
	 * 
	 * This enum is part of the 'sap/ui/webc/fiori/library' module export and must be accessed by the property 'BarDesign'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default BarDesign;
}

declare module "sap/ui/webc/fiori/FCLLayout" {
	import {FCLLayout} from "sap/ui/webc/fiori/library";

	/**
	 * Different types of FCLLayout.
	 * 
	 * This enum is part of the 'sap/ui/webc/fiori/library' module export and must be accessed by the property 'FCLLayout'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default FCLLayout;
}

declare module "sap/ui/webc/fiori/IllustrationMessageSize" {
	import {IllustrationMessageSize} from "sap/ui/webc/fiori/library";

	/**
	 * Different types of IllustrationMessageSize.
	 * 
	 * This enum is part of the 'sap/ui/webc/fiori/library' module export and must be accessed by the property 'IllustrationMessageSize'.
	 *
	 * @experimental (since 1.106.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.106.0
	*/
	export default IllustrationMessageSize;
}

declare module "sap/ui/webc/fiori/IllustrationMessageType" {
	import {IllustrationMessageType} from "sap/ui/webc/fiori/library";

	/**
	 * Different illustration types of Illustrated Message.
	 * 
	 * This enum is part of the 'sap/ui/webc/fiori/library' module export and must be accessed by the property 'IllustrationMessageType'.
	 *
	 * @experimental (since 1.95.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.95.0
	*/
	export default IllustrationMessageType;
}

declare module "sap/ui/webc/fiori/MediaGalleryItemLayout" {
	import {MediaGalleryItemLayout} from "sap/ui/webc/fiori/library";

	/**
	 * Defines the layout of the content displayed in the <code>ui5-media-gallery-item</code>.
	 * 
	 * This enum is part of the 'sap/ui/webc/fiori/library' module export and must be accessed by the property 'MediaGalleryItemLayout'.
	 *
	 * @experimental (since 1.99.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.99.0
	*/
	export default MediaGalleryItemLayout;
}

declare module "sap/ui/webc/fiori/MediaGalleryLayout" {
	import {MediaGalleryLayout} from "sap/ui/webc/fiori/library";

	/**
	 * Defines the layout type of the thumbnails list of the <code>ui5-media-gallery</code> component.
	 * 
	 * This enum is part of the 'sap/ui/webc/fiori/library' module export and must be accessed by the property 'MediaGalleryLayout'.
	 *
	 * @experimental (since 1.99.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.99.0
	*/
	export default MediaGalleryLayout;
}

declare module "sap/ui/webc/fiori/MediaGalleryMenuHorizontalAlign" {
	import {MediaGalleryMenuHorizontalAlign} from "sap/ui/webc/fiori/library";

	/**
	 * Defines the horizontal alignment of the thumbnails menu of the <code>ui5-media-gallery</code> component.
	 * 
	 * This enum is part of the 'sap/ui/webc/fiori/library' module export and must be accessed by the property 'MediaGalleryMenuHorizontalAlign'.
	 *
	 * @experimental (since 1.99.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.99.0
	*/
	export default MediaGalleryMenuHorizontalAlign;
}

declare module "sap/ui/webc/fiori/MediaGalleryMenuVerticalAlign" {
	import {MediaGalleryMenuVerticalAlign} from "sap/ui/webc/fiori/library";

	/**
	 * Types for the vertical alignment of the thumbnails menu of the <code>ui5-media-gallery</code> component.
	 * 
	 * This enum is part of the 'sap/ui/webc/fiori/library' module export and must be accessed by the property 'MediaGalleryMenuVerticalAlign'.
	 *
	 * @experimental (since 1.99.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.99.0
	*/
	export default MediaGalleryMenuVerticalAlign;
}

declare module "sap/ui/webc/fiori/PageBackgroundDesign" {
	import {PageBackgroundDesign} from "sap/ui/webc/fiori/library";

	/**
	 * Available Page Background Design.
	 * 
	 * This enum is part of the 'sap/ui/webc/fiori/library' module export and must be accessed by the property 'PageBackgroundDesign'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default PageBackgroundDesign;
}

declare module "sap/ui/webc/fiori/SideContentFallDown" {
	import {SideContentFallDown} from "sap/ui/webc/fiori/library";

	/**
	 * SideContent FallDown options.
	 * 
	 * This enum is part of the 'sap/ui/webc/fiori/library' module export and must be accessed by the property 'SideContentFallDown'.
	 *
	 * @experimental (since 1.99.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.99.0
	*/
	export default SideContentFallDown;
}

declare module "sap/ui/webc/fiori/SideContentPosition" {
	import {SideContentPosition} from "sap/ui/webc/fiori/library";

	/**
	 * Side Content position options.
	 * 
	 * This enum is part of the 'sap/ui/webc/fiori/library' module export and must be accessed by the property 'SideContentPosition'.
	 *
	 * @experimental (since 1.99.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.99.0
	*/
	export default SideContentPosition;
}

declare module "sap/ui/webc/fiori/SideContentVisibility" {
	import {SideContentVisibility} from "sap/ui/webc/fiori/library";

	/**
	 * Side Content visibility options.
	 * 
	 * This enum is part of the 'sap/ui/webc/fiori/library' module export and must be accessed by the property 'SideContentVisibility'.
	 *
	 * @experimental (since 1.99.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.99.0
	*/
	export default SideContentVisibility;
}

declare module "sap/ui/webc/fiori/TimelineLayout" {
	import {TimelineLayout} from "sap/ui/webc/fiori/library";

	/**
	 * Available Timeline layout orientation
	 * 
	 * This enum is part of the 'sap/ui/webc/fiori/library' module export and must be accessed by the property 'TimelineLayout'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default TimelineLayout;
}

declare module "sap/ui/webc/fiori/UploadState" {
	import {UploadState} from "sap/ui/webc/fiori/library";

	/**
	 * Different types of UploadState.
	 * 
	 * This enum is part of the 'sap/ui/webc/fiori/library' module export and must be accessed by the property 'UploadState'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default UploadState;
}

declare module "sap/ui/webc/fiori/ViewSettingsDialogMode" {
	import {ViewSettingsDialogMode} from "sap/ui/webc/fiori/library";

	/**
	 * Different types of Bar.
	 * 
	 * This enum is part of the 'sap/ui/webc/fiori/library' module export and must be accessed by the property 'ViewSettingsDialogMode'.
	 *
	 * @experimental (since 1.115.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.115.0
	*/
	export default ViewSettingsDialogMode;
}

declare module "sap/ui/webc/fiori/WizardContentLayout" {
	import {WizardContentLayout} from "sap/ui/webc/fiori/library";

	/**
	 * Enumeration for different content layouts of the <code>ui5-wizard</code>.
	 * 
	 * This enum is part of the 'sap/ui/webc/fiori/library' module export and must be accessed by the property 'WizardContentLayout'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default WizardContentLayout;
}
