// This file is generated by the createTypes script.

declare module "sap/ui/comp/navpopover/ChangeHandlerType" {
	import {navpopover} from "sap/ui/comp/library";

	/**
	 * Type of change handler type for link personalization.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'navpopover.ChangeHandlerType'.
	 *
	 * @public
	*/
	export default navpopover.ChangeHandlerType;
}

declare module "sap/ui/comp/personalization/AggregationRole" {
	import {personalization} from "sap/ui/comp/library";

	/**
	 * Provides enumeration sap.ui.comp.personalization.AggregationRole. A subset of aggregation roles used in table personalization.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'personalization.AggregationRole'.
	 *
	 * @public
	*/
	export default personalization.AggregationRole;
}

declare module "sap/ui/comp/personalization/ChangeType" {
	import {personalization} from "sap/ui/comp/library";

	/**
	 * Provides enumeration sap.ui.comp.personalization.ChangeType. A subset of changes done during table personalization.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'personalization.ChangeType'.
	 *
	 * @public
	*/
	export default personalization.ChangeType;
}

declare module "sap/ui/comp/personalization/ColumnType" {
	import {personalization} from "sap/ui/comp/library";

	/**
	 * Provides enumeration sap.ui.comp.personalization.ColumnType. A subset of column types that fit for table personalization.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'personalization.ColumnType'.
	 *
	 * @public
	*/
	export default personalization.ColumnType;
}

declare module "sap/ui/comp/personalization/ResetType" {
	import {personalization} from "sap/ui/comp/library";

	/**
	 * Provides enumeration sap.ui.comp.personalization.ResetType. A subset of reset types used in table personalization.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'personalization.ResetType'.
	 *
	 * @public
	*/
	export default personalization.ResetType;
}

declare module "sap/ui/comp/personalization/TableType" {
	import {personalization} from "sap/ui/comp/library";

	/**
	 * Provides enumeration sap.ui.comp.personalization.TableType. A subset of table types that fit for table personalization.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'personalization.TableType'.
	 *
	 * @public
	*/
	export default personalization.TableType;
}

declare module "sap/ui/comp/smartchart/SelectionMode" {
	import {smartchart} from "sap/ui/comp/library";

	/**
	 * Enumeration for supported selection mode in SmartChart
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smartchart.SelectionMode'.
	 *
	 * @public
	*/
	export default smartchart.SelectionMode;
}

declare module "sap/ui/comp/smartfield/ControlContextType" {
	import {smartfield} from "sap/ui/comp/library";

	/**
	 * Enumeration of the different contexts supported by the SmartField, if it is using an OData model.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smartfield.ControlContextType'.
	 *
	 * @public
	*/
	export default smartfield.ControlContextType;
}

declare module "sap/ui/comp/smartfield/ControlProposalType" {
	import {smartfield} from "sap/ui/comp/library";

	/**
	 * Enumeration of the different control proposals supported by the Smart Field, if it is using an OData model.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smartfield.ControlProposalType'.
	 *
	 * @public
	*/
	export default smartfield.ControlProposalType;
}

declare module "sap/ui/comp/smartfield/ControlType" {
	import {smartfield} from "sap/ui/comp/library";

	/**
	 * The available control types to configure the internal control selection of a SmartField control.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smartfield.ControlType'.
	 *
	 * @public
	*/
	export default smartfield.ControlType;
}

declare module "sap/ui/comp/smartfield/CriticalityRepresentationType" {
	import {smartfield} from "sap/ui/comp/library";

	/**
	 * The different options to visualize the ObjectStatus control.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smartfield.CriticalityRepresentationType'.
	 *
	 * @public
	*/
	export default smartfield.CriticalityRepresentationType;
}

declare module "sap/ui/comp/smartfield/DisplayBehaviour" {
	import {smartfield} from "sap/ui/comp/library";

	/**
	 * The different options to define display behavior for the value help of a SmartField control.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smartfield.DisplayBehaviour'.
	 *
	 * @public
	*/
	export default smartfield.DisplayBehaviour;
}

declare module "sap/ui/comp/smartfield/Importance" {
	import {smartfield} from "sap/ui/comp/library";

	/**
	 * Provides information about the importance of the field
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smartfield.Importance'.
	 *
	 * @public
	 * @since 1.87
	*/
	export default smartfield.Importance;
}

declare module "sap/ui/comp/smartfield/JSONType" {
	import {smartfield} from "sap/ui/comp/library";

	/**
	 * Enumeration of the different data types supported by the SmartField control, if it is using a JSON model.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smartfield.JSONType'.
	 *
	 * @public
	*/
	export default smartfield.JSONType;
}

declare module "sap/ui/comp/smartfield/TextInEditModeSource" {
	import {smartfield} from "sap/ui/comp/library";

	/**
	 * Enumeration of sources from which text values for <code>Codes</code>/<code>IDs</code> are fetched in edit mode. The text is usually visualized as description/text value for IDs, for example, for LT (Laptop).
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smartfield.TextInEditModeSource'.
	 *
	 * @public
	 * @since 1.54
	*/
	export default smartfield.TextInEditModeSource;
}

declare module "sap/ui/comp/smartfield/ValueHelpTitleSource" {
	import {smartfield} from "sap/ui/comp/library";

	/**
	 * Provides information about the ValueHelpTitleSource of the field
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smartfield.ValueHelpTitleSource'.
	 *
	 * @public
	 * @since 1.132
	*/
	export default smartfield.ValueHelpTitleSource;
}

declare module "sap/ui/comp/smartfilterbar/ControlType" {
	import {smartfilterbar} from "sap/ui/comp/library";

	/**
	 * The available control types to configure the internal control selection of a SmartFilterBar control.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smartfilterbar.ControlType'.
	 *
	 * @public
	*/
	export default smartfilterbar.ControlType;
}

declare module "sap/ui/comp/smartfilterbar/DisplayBehaviour" {
	import {smartfilterbar} from "sap/ui/comp/library";

	/**
	 * The different options to define display behavior for fields in the SmartFilter control.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smartfilterbar.DisplayBehaviour'.
	 *
	 * @public
	*/
	export default smartfilterbar.DisplayBehaviour;
}

declare module "sap/ui/comp/smartfilterbar/FilterType" {
	import {smartfilterbar} from "sap/ui/comp/library";

	/**
	 * The available filter types to configure the internal control of a SmartFilterBar control.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smartfilterbar.FilterType'.
	 *
	 * @public
	*/
	export default smartfilterbar.FilterType;
}

declare module "sap/ui/comp/smartfilterbar/MandatoryType" {
	import {smartfilterbar} from "sap/ui/comp/library";

	/**
	 * The different options to define mandatory state for fields in the SmartFilter control.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smartfilterbar.MandatoryType'.
	 *
	 * @public
	*/
	export default smartfilterbar.MandatoryType;
}

declare module "sap/ui/comp/smartfilterbar/SelectOptionSign" {
	import {smartfilterbar} from "sap/ui/comp/library";

	/**
	 * The different options to define Sign for Select Options used in SmartFilter control.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smartfilterbar.SelectOptionSign'.
	 *
	 * @public
	*/
	export default smartfilterbar.SelectOptionSign;
}

declare module "sap/ui/comp/smartform/Importance" {
	import {smartform} from "sap/ui/comp/library";

	/**
	 * Enumeration of SmartForm Importance types
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smartform.Importance'.
	 *
	 * @public
	 * @since 1.87
	*/
	export default smartform.Importance;
}

declare module "sap/ui/comp/smartform/SmartFormValidationMode" {
	import {smartform} from "sap/ui/comp/library";

	/**
	 * Enumeration of SmartForm validation mode.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smartform.SmartFormValidationMode'.
	 *
	 * @public
	 * @since 1.81
	*/
	export default smartform.SmartFormValidationMode;
}

declare module "sap/ui/comp/smartlist/ListType" {
	import {smartlist} from "sap/ui/comp/library";

	/**
	 * Provides enumeration sap.ui.comp.smartlist.ListType. A subset of list types that fit to a simple API returning one string.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smartlist.ListType'.
	 *
	 * @public
	 * @since 1.48
	*/
	export default smartlist.ListType;
}

declare module "sap/ui/comp/smarttable/ExportType" {
	import {smarttable} from "sap/ui/comp/library";

	/**
	 * Provides the type of services available for export in the <code>SmartTable</code> control.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smarttable.ExportType'.
	 *
	 * @public
	*/
	export default smarttable.ExportType;
}

declare module "sap/ui/comp/smarttable/InfoToolbarBehavior" {
	import {smarttable} from "sap/ui/comp/library";

	/**
	 * Enumeration <code>sap.ui.comp.smarttable.InfoToolbarBehavior</code> determines the behavior of the info toolbar in the <code>SmartTable</code> control.
	 * 
	 * The info toolbar represents the filters that are applied using the table personalization dialog.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smarttable.InfoToolbarBehavior'.
	 *
	 * @public
	 * @since 1.70
	*/
	export default smarttable.InfoToolbarBehavior;
}

declare module "sap/ui/comp/smarttable/TableType" {
	import {smarttable} from "sap/ui/comp/library";

	/**
	 * Provides enumeration sap.ui.comp.smarttable.TableType. A subset of table types that fit to a simple API returning one string.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smarttable.TableType'.
	 *
	 * @public
	*/
	export default smarttable.TableType;
}

declare module "sap/ui/comp/smartvariants/ChangeHandlerType" {
	import {smartvariants} from "sap/ui/comp/library";

	/**
	 * Enumeration for changes for personalization of variant favorites.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'smartvariants.ChangeHandlerType'.
	 *
	 * @public
	*/
	export default smartvariants.ChangeHandlerType;
}

declare module "sap/ui/comp/TextArrangementType" {
	import {TextArrangementType} from "sap/ui/comp/library";

	/**
	 * Enumeration of text arrangement types.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'TextArrangementType'.
	 *
	 * @public
	 * @since 1.60
	*/
	export default TextArrangementType;
}

declare module "sap/ui/comp/valuehelpdialog/ValueHelpRangeOperation" {
	import {valuehelpdialog} from "sap/ui/comp/library";

	/**
	 * The range operations supported by the <code>ValueHelpDialog</code> control.
	 * 
	 * This enum is part of the 'sap/ui/comp/library' module export and must be accessed by the property 'valuehelpdialog.ValueHelpRangeOperation'.
	 *
	 * @public
	*/
	export default valuehelpdialog.ValueHelpRangeOperation;
}
