// This file is generated by the createTypes script.

declare module "sap/ui/mdc/ChartP13nMode" {
	import {ChartP13nMode} from "sap/ui/mdc/library";

	/**
	 * Defines the personalization mode of the chart.
	 * 
	 * This enum is part of the 'sap/ui/mdc/library' module export and must be accessed by the property 'ChartP13nMode'.
	 *
	 * @deprecated (since 1.115.0) - please see {@link sap.ui.mdc.enums.ChartP13nMode}
	 * @restricted
	 * @since 1.75
	*/
	export default ChartP13nMode;
}

declare module "sap/ui/mdc/ChartToolbarActionType" {
	import {ChartToolbarActionType} from "sap/ui/mdc/library";

	/**
	 * Defines the types of chart actions in the toolbar.<br> Can be used to remove some of the default <code>ToolbarAction</code>. For more information, see {@link sap.ui.mdc.Chart#ignoreToolbarActions}.
	 * 
	 * This enum is part of the 'sap/ui/mdc/library' module export and must be accessed by the property 'ChartToolbarActionType'.
	 *
	 * @deprecated (since 1.115.0) - please see {@link sap.ui.mdc.enums.ChartToolbarActionType}
	 * @restricted
	 * @since 1.64
	*/
	export default ChartToolbarActionType;
}

declare module "sap/ui/mdc/FilterBarP13nMode" {
	import {FilterBarP13nMode} from "sap/ui/mdc/library";

	/**
	 * Defines the personalization mode of the filter bar.
	 * 
	 * This enum is part of the 'sap/ui/mdc/library' module export and must be accessed by the property 'FilterBarP13nMode'.
	 *
	 * @deprecated (since 1.115.0) - please see {@link sap.ui.mdc.enums.FilterBarP13nMode}
	 * @restricted
	 * @since 1.74
	*/
	export default FilterBarP13nMode;
}

declare module "sap/ui/mdc/GrowingMode" {
	import {GrowingMode} from "sap/ui/mdc/library";

	/**
	 * Defines the growing options of the responsive table.
	 * 
	 * This enum is part of the 'sap/ui/mdc/library' module export and must be accessed by the property 'GrowingMode'.
	 *
	 * @deprecated (since 1.115.0) - please see {@link sap.ui.mdc.enums.TableGrowingMode}
	 * @restricted
	 * @since 1.65
	*/
	export default GrowingMode;
}

declare module "sap/ui/mdc/MultiSelectMode" {
	import {MultiSelectMode} from "sap/ui/mdc/library";

	/**
	 * Enumeration of the <code>multiSelectMode</code> in <code>ListBase</code>.
	 * 
	 * This enum is part of the 'sap/ui/mdc/library' module export and must be accessed by the property 'MultiSelectMode'.
	 *
	 * @deprecated (since 1.115.0) - please see {@link sap.ui.mdc.enums.TableMultiSelectMode}
	 * @restricted
	*/
	export default MultiSelectMode;
}

declare module "sap/ui/mdc/RowAction" {
	import {RowAction} from "sap/ui/mdc/library";

	/**
	 * Defines the actions that can be used in the table.
	 * 
	 * This enum is part of the 'sap/ui/mdc/library' module export and must be accessed by the property 'RowAction'.
	 *
	 * @deprecated (since 1.115) - replaced by {@link sap.ui.mdc.enums.TableRowActionType}
	 * @restricted
	 * @since 1.60
	*/
	export default RowAction;
}

declare module "sap/ui/mdc/RowCountMode" {
	import {RowCountMode} from "sap/ui/mdc/library";

	/**
	 * Defines the row count mode of the GridTable.
	 * 
	 * This enum is part of the 'sap/ui/mdc/library' module export and must be accessed by the property 'RowCountMode'.
	 *
	 * @deprecated (since 1.115.0) - please see {@link sap.ui.mdc.enums.TableRowCountMode}
	 * @restricted
	 * @since 1.65
	*/
	export default RowCountMode;
}

declare module "sap/ui/mdc/SelectionMode" {
	import {SelectionMode} from "sap/ui/mdc/library";

	/**
	 * Defines the mode of the table.
	 * 
	 * This enum is part of the 'sap/ui/mdc/library' module export and must be accessed by the property 'SelectionMode'.
	 *
	 * @deprecated (since 1.115.0) - please see {@link sap.ui.mdc.enums.TableSelectionMode}
	 * @restricted
	 * @since 1.58
	*/
	export default SelectionMode;
}

declare module "sap/ui/mdc/TableP13nMode" {
	import {TableP13nMode} from "sap/ui/mdc/library";

	/**
	 * Defines the personalization mode of the table.
	 * 
	 * This enum is part of the 'sap/ui/mdc/library' module export and must be accessed by the property 'TableP13nMode'.
	 *
	 * @deprecated (since 1.115.0) - please see {@link sap.ui.mdc.enums.TableP13nMode}
	 * @restricted
	 * @since 1.62
	*/
	export default TableP13nMode;
}

declare module "sap/ui/mdc/TableType" {
	import {TableType} from "sap/ui/mdc/library";

	/**
	 * Defines the type of table used in the MDC table.
	 * 
	 * This enum is part of the 'sap/ui/mdc/library' module export and must be accessed by the property 'TableType'.
	 *
	 * @deprecated (since 1.115.0) - please see {@link sap.ui.mdc.enums.TableType}
	 * @restricted
	 * @since 1.58
	*/
	export default TableType;
}
