// This file is generated by the createTypes script.

declare module "sap/ushell/ContentNodeType" {
	import {ContentNodeType} from "sap/ushell/library";

	/**
	 * Denotes the types of the content nodes.
	 * 
	 * This enum is part of the 'sap/ushell/library' module export and must be accessed by the property 'ContentNodeType'.
	 *
	 * @public
	*/
	export default ContentNodeType;
}

declare module "sap/ushell/NavigationState" {
	import {NavigationState} from "sap/ushell/library";

	/**
	 * The state of a navigation operation
	 * 
	 * This enum is part of the 'sap/ushell/library' module export and must be accessed by the property 'NavigationState'.
	 *
	 * @deprecated (since 1.136)
	 * @public
	*/
	export default NavigationState;
}

declare module "sap/ushell/ui/launchpad/ViewPortState" {
	import {ui} from "sap/ushell/library";

	/**
	 * Denotes display states of the viewport
	 * 
	 * This enum is part of the 'sap/ushell/library' module export and must be accessed by the property 'ui.launchpad.ViewPortState'.
	 *
	 * @deprecated (since 1.120) - The ViewPortState is related to Fiori2 and not used anymore.
	 * @public
	*/
	export default ui.launchpad.ViewPortState;
}
