// This file is generated by the createTypes script.

declare module "sap/ui/integration/AttributesLayoutType" {
	import {AttributesLayoutType} from "sap/ui/integration/library";

	/**
	 * Defines the layout type of the List Card attributes.
	 * 
	 * This enum is part of the 'sap/ui/integration/library' module export and must be accessed by the property 'AttributesLayoutType'.
	 *
	 * @public
	 * @since 1.96
	*/
	export default AttributesLayoutType;
}

declare module "sap/ui/integration/CardActionType" {
	import {CardActionType} from "sap/ui/integration/library";

	/**
	 * Enumeration of possible card action types.
	 * 
	 * This enum is part of the 'sap/ui/integration/library' module export and must be accessed by the property 'CardActionType'.
	 *
	 * @experimental (since 1.64) - Disclaimer: this property is in a beta state - incompatible API changes may be done before its official public release. Use at your own discretion.
	 * @public
	*/
	export default CardActionType;
}

declare module "sap/ui/integration/CardArea" {
	import {CardArea} from "sap/ui/integration/library";

	/**
	 * Defines the areas in a card.
	 * 
	 * This enum is part of the 'sap/ui/integration/library' module export and must be accessed by the property 'CardArea'.
	 *
	 * @public
	 * @since 1.86
	*/
	export default CardArea;
}

declare module "sap/ui/integration/CardBlockingMessageType" {
	import {CardBlockingMessageType} from "sap/ui/integration/library";

	/**
	 * Card blocking message types.
	 * 
	 * This enum is part of the 'sap/ui/integration/library' module export and must be accessed by the property 'CardBlockingMessageType'.
	 *
	 * @experimental (since 1.114)
	 * @public
	*/
	export default CardBlockingMessageType;
}

declare module "sap/ui/integration/CardDataMode" {
	import {CardDataMode} from "sap/ui/integration/library";

	/**
	 * Possible data modes for <code>{@link sap.ui.integration.widgets.Card}</code>.
	 * 
	 * This enum is part of the 'sap/ui/integration/library' module export and must be accessed by the property 'CardDataMode'.
	 *
	 * @experimental (since 1.65)
	 * @public
	 * @since 1.65
	*/
	export default CardDataMode;
}

declare module "sap/ui/integration/CardDesign" {
	import {CardDesign} from "sap/ui/integration/library";

	/**
	 * Possible designs for <code>{@link sap.ui.integration.widgets.Card}</code>.
	 * 
	 * This enum is part of the 'sap/ui/integration/library' module export and must be accessed by the property 'CardDesign'.
	 *
	 * @experimental (since 1.109)
	 * @public
	 * @since 1.109
	*/
	export default CardDesign;
}

declare module "sap/ui/integration/CardDisplayVariant" {
	import {CardDisplayVariant} from "sap/ui/integration/library";

	/**
	 * Possible variants for <code>{@link sap.ui.integration.widgets.Card}</code> rendering and behavior.
	 * 
	 * This enum is part of the 'sap/ui/integration/library' module export and must be accessed by the property 'CardDisplayVariant'.
	 *
	 * @experimental (since 1.118) - For usage only by Work Zone.
	 * @public
	 * @since 1.118
	*/
	export default CardDisplayVariant;
}

declare module "sap/ui/integration/CardMessageType" {
	import {CardMessageType} from "sap/ui/integration/library";

	/**
	 * Card message strip types.
	 * 
	 * This enum is part of the 'sap/ui/integration/library' module export and must be accessed by the property 'CardMessageType'.
	 *
	 * @experimental (since 1.128)
	 * @public
	*/
	export default CardMessageType;
}

declare module "sap/ui/integration/CardOverflow" {
	import {CardOverflow} from "sap/ui/integration/library";

	/**
	 * Determines the overflow behaviour of the card.
	 * 
	 * This enum is part of the 'sap/ui/integration/library' module export and must be accessed by the property 'CardOverflow'.
	 *
	 * @experimental (since 1.133)
	 * @public
	 * @since 1.133
	*/
	export default CardOverflow;
}

declare module "sap/ui/integration/CardPreviewMode" {
	import {CardPreviewMode} from "sap/ui/integration/library";

	/**
	 * Preview modes for <code>{@link sap.ui.integration.widgets.Card}</code>. Helpful in scenarios when the end user is choosing or configuring a card.
	 * 
	 * This enum is part of the 'sap/ui/integration/library' module export and must be accessed by the property 'CardPreviewMode'.
	 *
	 * @experimental (since 1.112)
	 * @public
	 * @since 1.112
	*/
	export default CardPreviewMode;
}
