// This file is generated by the createTypes script.

declare module "sap/ui/table/GroupEventType" {
	import {GroupEventType} from "sap/ui/table/library";

	/**
	 * Details about the group event to distinguish between different actions associated with grouping
	 * 
	 * This enum is part of the 'sap/ui/table/library' module export and must be accessed by the property 'GroupEventType'.
	 *
	 * @public
	*/
	export default GroupEventType;
}

declare module "sap/ui/table/NavigationMode" {
	import {NavigationMode} from "sap/ui/table/library";

	/**
	 * Navigation mode of the table
	 * 
	 * This enum is part of the 'sap/ui/table/library' module export and must be accessed by the property 'NavigationMode'.
	 *
	 * @deprecated (since 1.38) - the concept has been discarded.
	 * @public
	*/
	export default NavigationMode;
}

declare module "sap/ui/table/ResetAllMode" {
	import {ResetAllMode} from "sap/ui/table/library";

	/**
	 * Enumeration of the <code>ResetAllMode</code> that can be used in a <code>TablePersoController</code>.
	 * 
	 * This enum is part of the 'sap/ui/table/library' module export and must be accessed by the property 'ResetAllMode'.
	 *
	 * @deprecated (since 1.115) - replaced by {@link sap.m.p13n.Engine}
	 * @public
	*/
	export default ResetAllMode;
}

declare module "sap/ui/table/RowActionType" {
	import {RowActionType} from "sap/ui/table/library";

	/**
	 * Row Action types.
	 * 
	 * This enum is part of the 'sap/ui/table/library' module export and must be accessed by the property 'RowActionType'.
	 *
	 * @public
	*/
	export default RowActionType;
}

declare module "sap/ui/table/SelectionBehavior" {
	import {SelectionBehavior} from "sap/ui/table/library";

	/**
	 * Selection behavior of the table
	 * 
	 * This enum is part of the 'sap/ui/table/library' module export and must be accessed by the property 'SelectionBehavior'.
	 *
	 * @public
	*/
	export default SelectionBehavior;
}

declare module "sap/ui/table/SelectionMode" {
	import {SelectionMode} from "sap/ui/table/library";

	/**
	 * Selection mode of the table
	 * 
	 * This enum is part of the 'sap/ui/table/library' module export and must be accessed by the property 'SelectionMode'.
	 *
	 * @public
	*/
	export default SelectionMode;
}

declare module "sap/ui/table/SharedDomRef" {
	import {SharedDomRef} from "sap/ui/table/library";

	/**
	 * Shared DOM Reference IDs of the table.
	 * 
	 * Contains IDs of shared DOM references, which should be accessible to inheriting controls via getDomRef() function.
	 * 
	 * This enum is part of the 'sap/ui/table/library' module export and must be accessed by the property 'SharedDomRef'.
	 *
	 * @public
	*/
	export default SharedDomRef;
}

declare module "sap/ui/table/SortOrder" {
	import {SortOrder} from "sap/ui/table/library";

	/**
	 * Sort order of a column
	 * 
	 * This enum is part of the 'sap/ui/table/library' module export and must be accessed by the property 'SortOrder'.
	 *
	 * @deprecated (since 1.120) - replaced with <code>sap.ui.core.SortOrder</code>
	 * @public
	*/
	export default SortOrder;
}

declare module "sap/ui/table/VisibleRowCountMode" {
	import {VisibleRowCountMode} from "sap/ui/table/library";

	/**
	 * VisibleRowCountMode of the table
	 * 
	 * This enum is part of the 'sap/ui/table/library' module export and must be accessed by the property 'VisibleRowCountMode'.
	 *
	 * @deprecated (since 1.119) - see the <code>rowMode</code> aggregation of <code>sap.ui.table.Table</code> for more details.
	 * @public
	*/
	export default VisibleRowCountMode;
}
