// This file is generated by the createTypes script.

declare module "sap/chart/coloring/GradationDivergingColorScheme" {
	import {coloring} from "sap/chart/library";

	/**
	 * Enumeration for supported Gradation diverging color scheme in analytical chart
	 * 
	 * This enum is part of the 'sap/chart/library' module export and must be accessed by the property 'coloring.GradationDivergingColorScheme'.
	 *
	 * @public
	*/
	export default coloring.GradationDivergingColorScheme;
}

declare module "sap/chart/coloring/GradationSaturation" {
	import {coloring} from "sap/chart/library";

	/**
	 * Enumeration for supported Gradation color saturation in analytical chart
	 * 
	 * This enum is part of the 'sap/chart/library' module export and must be accessed by the property 'coloring.GradationSaturation'.
	 *
	 * @public
	*/
	export default coloring.GradationSaturation;
}

declare module "sap/chart/coloring/GradationSingleColorScheme" {
	import {coloring} from "sap/chart/library";

	/**
	 * Enumeration for supported Gradation single color scheme in analytical chart
	 * 
	 * This enum is part of the 'sap/chart/library' module export and must be accessed by the property 'coloring.GradationSingleColorScheme'.
	 *
	 * @public
	*/
	export default coloring.GradationSingleColorScheme;
}

declare module "sap/chart/coloring/GradationTargetColorScheme" {
	import {coloring} from "sap/chart/library";

	/**
	 * Enumeration for supported Gradation target color scheme in analytical chart
	 * 
	 * This enum is part of the 'sap/chart/library' module export and must be accessed by the property 'coloring.GradationTargetColorScheme'.
	 *
	 * @public
	*/
	export default coloring.GradationTargetColorScheme;
}

declare module "sap/chart/coloring/ImprovementDirectionType" {
	import {coloring} from "sap/chart/library";

	/**
	 * Enumeration for supported ImprovementDirection types in analytical chart
	 * 
	 * This enum is part of the 'sap/chart/library' module export and must be accessed by the property 'coloring.ImprovementDirectionType'.
	 *
	 * @public
	*/
	export default coloring.ImprovementDirectionType;
}

declare module "sap/chart/MessageId" {
	import {MessageId} from "sap/chart/library";

	/**
	 * Enumeration for supported message types in analytical chart.
	 * 
	 * This enum is part of the 'sap/chart/library' module export and must be accessed by the property 'MessageId'.
	 *
	 * @public
	*/
	export default MessageId;
}

declare module "sap/chart/SelectionBehavior" {
	import {SelectionBehavior} from "sap/chart/library";

	/**
	 * Enumeration for supported selection behavior in analytical chart
	 * 
	 * This enum is part of the 'sap/chart/library' module export and must be accessed by the property 'SelectionBehavior'.
	 *
	 * @public
	*/
	export default SelectionBehavior;
}

declare module "sap/chart/SelectionMode" {
	import {SelectionMode} from "sap/chart/library";

	/**
	 * Enumeration for supported selection mode in analytical chart
	 * 
	 * This enum is part of the 'sap/chart/library' module export and must be accessed by the property 'SelectionMode'.
	 *
	 * @public
	*/
	export default SelectionMode;
}
