// This file is generated by the createTypes script.

declare module "sap/ui/vbm/ClusterInfoType" {
	import {ClusterInfoType} from "sap/ui/vbm/library";

	/**
	 * Cluster Info Type
	 * 
	 * This enum is part of the 'sap/ui/vbm/library' module export and must be accessed by the property 'ClusterInfoType'.
	 *
	 * @public
	*/
	export default ClusterInfoType;
}

declare module "sap/ui/vbm/RouteType" {
	import {RouteType} from "sap/ui/vbm/library";

	/**
	 * Route type, determining how line between start and endpoint should be drawn.
	 * 
	 * This enum is part of the 'sap/ui/vbm/library' module export and must be accessed by the property 'RouteType'.
	 *
	 * @public
	*/
	export default RouteType;
}

declare module "sap/ui/vbm/SemanticType" {
	import {SemanticType} from "sap/ui/vbm/library";

	/**
	 * Semantic type with pre-defined display properties, like colors, icon, pin image, and so on. Semantic types enforce to fiori guidelines.
	 * 
	 * This enum is part of the 'sap/ui/vbm/library' module export and must be accessed by the property 'SemanticType'.
	 *
	 * @public
	*/
	export default SemanticType;
}
