// This file is generated by the createTypes script.

declare module "sap/ui/ux3/ActionBarSocialActions" {
	import {ActionBarSocialActions} from "sap/ui/ux3/library";

	/**
	 * Enumeration of available standard actions for 'sap.ui.ux3.ActionBar'. To be used as parameters for function 'sap.ui.ux3.ActionBar.getSocialAction'.
	 * 
	 * This enum is part of the 'sap/ui/ux3/library' module export and must be accessed by the property 'ActionBarSocialActions'.
	 *
	 * @experimental (since 1.2) - API is not yet finished and might change completely
	 * @deprecated (since 1.38)
	 * @public
	*/
	export default ActionBarSocialActions;
}

declare module "sap/ui/ux3/ExactOrder" {
	import {ExactOrder} from "sap/ui/ux3/library";

	/**
	 * Defines the order of the sub lists of a list in the ExactBrowser.
	 * 
	 * This enum is part of the 'sap/ui/ux3/library' module export and must be accessed by the property 'ExactOrder'.
	 *
	 * @deprecated (since 1.38)
	 * @public
	 * @since 1.7.1
	*/
	export default ExactOrder;
}

declare module "sap/ui/ux3/FeederType" {
	import {FeederType} from "sap/ui/ux3/library";

	/**
	 * Type of a Feeder.
	 * 
	 * This enum is part of the 'sap/ui/ux3/library' module export and must be accessed by the property 'FeederType'.
	 *
	 * @experimental (since 1.2) - The whole Feed/Feeder API is still under discussion, significant changes are likely. Especially text presentation (e.g. @-references and formatted text) is not final. Also the Feed model topic is still open.
	 * @deprecated (since 1.38)
	 * @public
	*/
	export default FeederType;
}

declare module "sap/ui/ux3/FollowActionState" {
	import {FollowActionState} from "sap/ui/ux3/library";

	/**
	 * Defines the states of the follow action
	 * 
	 * This enum is part of the 'sap/ui/ux3/library' module export and must be accessed by the property 'FollowActionState'.
	 *
	 * @deprecated (since 1.38)
	 * @public
	*/
	export default FollowActionState;
}

declare module "sap/ui/ux3/NotificationBarStatus" {
	import {NotificationBarStatus} from "sap/ui/ux3/library";

	/**
	 * This entries are used to set the visibility status of a NotificationBar
	 * 
	 * This enum is part of the 'sap/ui/ux3/library' module export and must be accessed by the property 'NotificationBarStatus'.
	 *
	 * @deprecated (since 1.38)
	 * @public
	*/
	export default NotificationBarStatus;
}

declare module "sap/ui/ux3/ShellDesignType" {
	import {ShellDesignType} from "sap/ui/ux3/library";

	/**
	 * Available shell design types.
	 * 
	 * This enum is part of the 'sap/ui/ux3/library' module export and must be accessed by the property 'ShellDesignType'.
	 *
	 * @deprecated (since 1.38)
	 * @public
	 * @since 1.12.0
	*/
	export default ShellDesignType;
}

declare module "sap/ui/ux3/ShellHeaderType" {
	import {ShellHeaderType} from "sap/ui/ux3/library";

	/**
	 * Available shell header display types.
	 * 
	 * This enum is part of the 'sap/ui/ux3/library' module export and must be accessed by the property 'ShellHeaderType'.
	 *
	 * @deprecated (since 1.38)
	 * @public
	*/
	export default ShellHeaderType;
}

declare module "sap/ui/ux3/ThingViewerHeaderType" {
	import {ThingViewerHeaderType} from "sap/ui/ux3/library";

	/**
	 * Available ThingViewer header display types.
	 * 
	 * This enum is part of the 'sap/ui/ux3/library' module export and must be accessed by the property 'ThingViewerHeaderType'.
	 *
	 * @deprecated (since 1.38)
	 * @public
	 * @since 1.16.3
	*/
	export default ThingViewerHeaderType;
}

declare module "sap/ui/ux3/VisibleItemCountMode" {
	import {VisibleItemCountMode} from "sap/ui/ux3/library";

	/**
	 * VisibleItemCountMode of the FacetFilter defines if the FacetFilter takes the whole available height (Auto) in the surrounding container, or is so high as needed to show 5 Items ("Fixed " - default).
	 * 
	 * This enum is part of the 'sap/ui/ux3/library' module export and must be accessed by the property 'VisibleItemCountMode'.
	 *
	 * @deprecated (since 1.38)
	 * @public
	*/
	export default VisibleItemCountMode;
}
