// This file is generated by the createTypes script.

declare module "sap/ui/webc/main/AvatarColorScheme" {
	import {AvatarColorScheme} from "sap/ui/webc/main/library";

	/**
	 * Different types of AvatarColorScheme.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'AvatarColorScheme'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default AvatarColorScheme;
}

declare module "sap/ui/webc/main/AvatarGroupType" {
	import {AvatarGroupType} from "sap/ui/webc/main/library";

	/**
	 * Different types of AvatarGroupType.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'AvatarGroupType'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default AvatarGroupType;
}

declare module "sap/ui/webc/main/AvatarShape" {
	import {AvatarShape} from "sap/ui/webc/main/library";

	/**
	 * Different types of AvatarShape.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'AvatarShape'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default AvatarShape;
}

declare module "sap/ui/webc/main/AvatarSize" {
	import {AvatarSize} from "sap/ui/webc/main/library";

	/**
	 * Different types of AvatarSize.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'AvatarSize'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default AvatarSize;
}

declare module "sap/ui/webc/main/BackgroundDesign" {
	import {BackgroundDesign} from "sap/ui/webc/main/library";

	/**
	 * Defines background designs.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'BackgroundDesign'.
	 *
	 * @experimental (since 1.115.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.115.0
	*/
	export default BackgroundDesign;
}

declare module "sap/ui/webc/main/BorderDesign" {
	import {BorderDesign} from "sap/ui/webc/main/library";

	/**
	 * Defines border designs.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'BorderDesign'.
	 *
	 * @experimental (since 1.115.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.115.0
	*/
	export default BorderDesign;
}

declare module "sap/ui/webc/main/BreadcrumbsDesign" {
	import {BreadcrumbsDesign} from "sap/ui/webc/main/library";

	/**
	 * Different Breadcrumbs designs.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'BreadcrumbsDesign'.
	 *
	 * @experimental (since 1.95.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.95.0
	*/
	export default BreadcrumbsDesign;
}

declare module "sap/ui/webc/main/BreadcrumbsSeparatorStyle" {
	import {BreadcrumbsSeparatorStyle} from "sap/ui/webc/main/library";

	/**
	 * Different Breadcrumbs separator styles.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'BreadcrumbsSeparatorStyle'.
	 *
	 * @experimental (since 1.95.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.95.0
	*/
	export default BreadcrumbsSeparatorStyle;
}

declare module "sap/ui/webc/main/BusyIndicatorSize" {
	import {BusyIndicatorSize} from "sap/ui/webc/main/library";

	/**
	 * Different BusyIndicator sizes.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'BusyIndicatorSize'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default BusyIndicatorSize;
}

declare module "sap/ui/webc/main/ButtonDesign" {
	import {ButtonDesign} from "sap/ui/webc/main/library";

	/**
	 * Different Button designs.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'ButtonDesign'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default ButtonDesign;
}

declare module "sap/ui/webc/main/ButtonType" {
	import {ButtonType} from "sap/ui/webc/main/library";

	/**
	 * Determines if the button has special form-related functionality.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'ButtonType'.
	 *
	 * @experimental (since 1.120.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.120.0
	*/
	export default ButtonType;
}

declare module "sap/ui/webc/main/CalendarSelectionMode" {
	import {CalendarSelectionMode} from "sap/ui/webc/main/library";

	/**
	 * Different Calendar selection mode.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'CalendarSelectionMode'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default CalendarSelectionMode;
}

declare module "sap/ui/webc/main/CarouselArrowsPlacement" {
	import {CarouselArrowsPlacement} from "sap/ui/webc/main/library";

	/**
	 * Different Carousel arrows placement.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'CarouselArrowsPlacement'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default CarouselArrowsPlacement;
}

declare module "sap/ui/webc/main/CarouselPageIndicatorStyle" {
	import {CarouselPageIndicatorStyle} from "sap/ui/webc/main/library";

	/**
	 * Different Carousel page indicator styles.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'CarouselPageIndicatorStyle'.
	 *
	 * @experimental (since 1.115.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.115.0
	*/
	export default CarouselPageIndicatorStyle;
}

declare module "sap/ui/webc/main/ComboBoxFilter" {
	import {ComboBoxFilter} from "sap/ui/webc/main/library";

	/**
	 * Different filtering types of the ComboBox.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'ComboBoxFilter'.
	 *
	 * @experimental (since 1.115.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.115.0
	*/
	export default ComboBoxFilter;
}

declare module "sap/ui/webc/main/HasPopup" {
	import {HasPopup} from "sap/ui/webc/main/library";

	/**
	 * Different types of HasPopup.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'HasPopup'.
	 *
	 * @experimental (since 1.99.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.99.0
	*/
	export default HasPopup;
}

declare module "sap/ui/webc/main/IconDesign" {
	import {IconDesign} from "sap/ui/webc/main/library";

	/**
	 * Different Icon semantic designs.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'IconDesign'.
	 *
	 * @experimental (since 1.115.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.115.0
	*/
	export default IconDesign;
}

declare module "sap/ui/webc/main/InputType" {
	import {InputType} from "sap/ui/webc/main/library";

	/**
	 * Different input types.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'InputType'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default InputType;
}

declare module "sap/ui/webc/main/LinkDesign" {
	import {LinkDesign} from "sap/ui/webc/main/library";

	/**
	 * Different link designs.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'LinkDesign'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default LinkDesign;
}

declare module "sap/ui/webc/main/ListGrowingMode" {
	import {ListGrowingMode} from "sap/ui/webc/main/library";

	/**
	 * Different list growing modes.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'ListGrowingMode'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default ListGrowingMode;
}

declare module "sap/ui/webc/main/ListItemType" {
	import {ListItemType} from "sap/ui/webc/main/library";

	/**
	 * Different list item types.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'ListItemType'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default ListItemType;
}

declare module "sap/ui/webc/main/ListMode" {
	import {ListMode} from "sap/ui/webc/main/library";

	/**
	 * Different list modes.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'ListMode'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default ListMode;
}

declare module "sap/ui/webc/main/ListSeparators" {
	import {ListSeparators} from "sap/ui/webc/main/library";

	/**
	 * Different types of list items separators.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'ListSeparators'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default ListSeparators;
}

declare module "sap/ui/webc/main/MessageStripDesign" {
	import {MessageStripDesign} from "sap/ui/webc/main/library";

	/**
	 * MessageStrip designs.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'MessageStripDesign'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default MessageStripDesign;
}

declare module "sap/ui/webc/main/PanelAccessibleRole" {
	import {PanelAccessibleRole} from "sap/ui/webc/main/library";

	/**
	 * Panel accessible roles.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'PanelAccessibleRole'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default PanelAccessibleRole;
}

declare module "sap/ui/webc/main/PopoverHorizontalAlign" {
	import {PopoverHorizontalAlign} from "sap/ui/webc/main/library";

	/**
	 * Popover horizontal align types.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'PopoverHorizontalAlign'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default PopoverHorizontalAlign;
}

declare module "sap/ui/webc/main/PopoverPlacementType" {
	import {PopoverPlacementType} from "sap/ui/webc/main/library";

	/**
	 * Popover placement types.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'PopoverPlacementType'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default PopoverPlacementType;
}

declare module "sap/ui/webc/main/PopoverVerticalAlign" {
	import {PopoverVerticalAlign} from "sap/ui/webc/main/library";

	/**
	 * Popover vertical align types.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'PopoverVerticalAlign'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default PopoverVerticalAlign;
}

declare module "sap/ui/webc/main/PopupAccessibleRole" {
	import {PopupAccessibleRole} from "sap/ui/webc/main/library";

	/**
	 * Popup accessible roles.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'PopupAccessibleRole'.
	 *
	 * @experimental (since 1.115.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.115.0
	*/
	export default PopupAccessibleRole;
}

declare module "sap/ui/webc/main/Priority" {
	import {Priority} from "sap/ui/webc/main/library";

	/**
	 * Different types of Priority.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'Priority'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default Priority;
}

declare module "sap/ui/webc/main/SegmentedButtonMode" {
	import {SegmentedButtonMode} from "sap/ui/webc/main/library";

	/**
	 * Different SegmentedButton modes.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'SegmentedButtonMode'.
	 *
	 * @experimental (since 1.115.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.115.0
	*/
	export default SegmentedButtonMode;
}

declare module "sap/ui/webc/main/SemanticColor" {
	import {SemanticColor} from "sap/ui/webc/main/library";

	/**
	 * Different types of SemanticColor.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'SemanticColor'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default SemanticColor;
}

declare module "sap/ui/webc/main/SwitchDesign" {
	import {SwitchDesign} from "sap/ui/webc/main/library";

	/**
	 * Different types of Switch designs.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'SwitchDesign'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default SwitchDesign;
}

declare module "sap/ui/webc/main/TabContainerBackgroundDesign" {
	import {TabContainerBackgroundDesign} from "sap/ui/webc/main/library";

	/**
	 * Background design for the header and content of TabContainer.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'TabContainerBackgroundDesign'.
	 *
	 * @experimental (since 1.115.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.115.0
	*/
	export default TabContainerBackgroundDesign;
}

declare module "sap/ui/webc/main/TabLayout" {
	import {TabLayout} from "sap/ui/webc/main/library";

	/**
	 * Tab layout of TabContainer.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'TabLayout'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default TabLayout;
}

declare module "sap/ui/webc/main/TableColumnPopinDisplay" {
	import {TableColumnPopinDisplay} from "sap/ui/webc/main/library";

	/**
	 * Table cell popin display.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'TableColumnPopinDisplay'.
	 *
	 * @experimental (since 1.115.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.115.0
	*/
	export default TableColumnPopinDisplay;
}

declare module "sap/ui/webc/main/TableGrowingMode" {
	import {TableGrowingMode} from "sap/ui/webc/main/library";

	/**
	 * Different table growing modes.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'TableGrowingMode'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default TableGrowingMode;
}

declare module "sap/ui/webc/main/TableMode" {
	import {TableMode} from "sap/ui/webc/main/library";

	/**
	 * Different table modes.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'TableMode'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default TableMode;
}

declare module "sap/ui/webc/main/TableRowType" {
	import {TableRowType} from "sap/ui/webc/main/library";

	/**
	 * Different table row types.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'TableRowType'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default TableRowType;
}

declare module "sap/ui/webc/main/TabsOverflowMode" {
	import {TabsOverflowMode} from "sap/ui/webc/main/library";

	/**
	 * Tabs overflow mode in TabContainer.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'TabsOverflowMode'.
	 *
	 * @experimental (since 1.99.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.99.0
	*/
	export default TabsOverflowMode;
}

declare module "sap/ui/webc/main/TitleLevel" {
	import {TitleLevel} from "sap/ui/webc/main/library";

	/**
	 * Different types of Title level.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'TitleLevel'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default TitleLevel;
}

declare module "sap/ui/webc/main/ToastPlacement" {
	import {ToastPlacement} from "sap/ui/webc/main/library";

	/**
	 * Toast placement.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'ToastPlacement'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default ToastPlacement;
}

declare module "sap/ui/webc/main/ToolbarAlign" {
	import {ToolbarAlign} from "sap/ui/webc/main/library";

	/**
	 * Defines which direction the items of ui5-toolbar will be aligned.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'ToolbarAlign'.
	 *
	 * @experimental (since 1.120.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.120.0
	*/
	export default ToolbarAlign;
}

declare module "sap/ui/webc/main/ToolbarItemOverflowBehavior" {
	import {ToolbarItemOverflowBehavior} from "sap/ui/webc/main/library";

	/**
	 * Defines the priority of the toolbar item to go inside overflow popover.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'ToolbarItemOverflowBehavior'.
	 *
	 * @experimental (since 1.120.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.120.0
	*/
	export default ToolbarItemOverflowBehavior;
}

declare module "sap/ui/webc/main/WrappingType" {
	import {WrappingType} from "sap/ui/webc/main/library";

	/**
	 * Different types of wrapping.
	 * 
	 * This enum is part of the 'sap/ui/webc/main/library' module export and must be accessed by the property 'WrappingType'.
	 *
	 * @experimental (since 1.92.0) - This API is experimental and might change significantly.
	 * @public
	 * @since 1.92.0
	*/
	export default WrappingType;
}
