// This file is generated by the createTypes script.

declare module "sap/suite/ui/microchart/AreaMicroChartViewType" {
	import {AreaMicroChartViewType} from "sap/suite/ui/microchart/library";

	/**
	 * Enum of available views for the area micro chart concerning the position of the labels.
	 * 
	 * This enum is part of the 'sap/suite/ui/microchart/library' module export and must be accessed by the property 'AreaMicroChartViewType'.
	 *
	 * @public
	 * @since 1.34
	*/
	export default AreaMicroChartViewType;
}

declare module "sap/suite/ui/microchart/BulletMicroChartModeType" {
	import {BulletMicroChartModeType} from "sap/suite/ui/microchart/library";

	/**
	 * Defines if the horizontal bar represents a current value only or if it represents the delta between a current value and a threshold value.
	 * 
	 * This enum is part of the 'sap/suite/ui/microchart/library' module export and must be accessed by the property 'BulletMicroChartModeType'.
	 *
	 * @public
	 * @since 1.34
	*/
	export default BulletMicroChartModeType;
}

declare module "sap/suite/ui/microchart/CommonBackgroundType" {
	import {CommonBackgroundType} from "sap/suite/ui/microchart/library";

	/**
	 * Lists the available theme-specific background colors.
	 * 
	 * This enum is part of the 'sap/suite/ui/microchart/library' module export and must be accessed by the property 'CommonBackgroundType'.
	 *
	 * @public
	 * @since 1.34
	*/
	export default CommonBackgroundType;
}

declare module "sap/suite/ui/microchart/ComparisonMicroChartViewType" {
	import {ComparisonMicroChartViewType} from "sap/suite/ui/microchart/library";

	/**
	 * Lists the views of the comparison micro chart concerning the position of titles and labels.
	 * 
	 * This enum is part of the 'sap/suite/ui/microchart/library' module export and must be accessed by the property 'ComparisonMicroChartViewType'.
	 *
	 * @public
	 * @since 1.34
	*/
	export default ComparisonMicroChartViewType;
}

declare module "sap/suite/ui/microchart/DeltaMicroChartViewType" {
	import {DeltaMicroChartViewType} from "sap/suite/ui/microchart/library";

	/**
	 * Lists the views of the delta micro chart concerning the position of titles.
	 * 
	 * This enum is part of the 'sap/suite/ui/microchart/library' module export and must be accessed by the property 'DeltaMicroChartViewType'.
	 *
	 * @public
	 * @since 1.61
	*/
	export default DeltaMicroChartViewType;
}

declare module "sap/suite/ui/microchart/HorizontalAlignmentType" {
	import {HorizontalAlignmentType} from "sap/suite/ui/microchart/library";

	/**
	 * Alignment type for the microchart content.
	 * 
	 * This enum is part of the 'sap/suite/ui/microchart/library' module export and must be accessed by the property 'HorizontalAlignmentType'.
	 *
	 * @public
	 * @since 1.62
	*/
	export default HorizontalAlignmentType;
}

declare module "sap/suite/ui/microchart/LineType" {
	import {LineType} from "sap/suite/ui/microchart/library";

	/**
	 * Type of the microchart line.
	 * 
	 * This enum is part of the 'sap/suite/ui/microchart/library' module export and must be accessed by the property 'LineType'.
	 *
	 * @public
	 * @since 1.60
	*/
	export default LineType;
}

declare module "sap/suite/ui/microchart/MicroChartColorType" {
	import {MicroChartColorType} from "sap/suite/ui/microchart/library";

	/**
	 * Colors to highlight certain UI chart elements.
	 * 
	 * Instead of the <code>ValueState</code>, semantic colors must be defined by the application.
	 * 
	 * This enum is part of the 'sap/suite/ui/microchart/library' module export and must be accessed by the property 'MicroChartColorType'.
	 *
	 * @public
	 * @since 1.129
	*/
	export default MicroChartColorType;
}
