// This file is generated by the createTypes script.

declare module "sap/collaboration/AppType" {
	import {AppType} from "sap/collaboration/library";

	/**
	 * Application Type (Mode)
	 * 
	 * This enum is part of the 'sap/collaboration/library' module export and must be accessed by the property 'AppType'.
	 *
	 * @public
	*/
	export default AppType;
}

declare module "sap/collaboration/DisplayFeedType" {
	import {DisplayFeedType} from "sap/collaboration/library";

	/**
	 * Feed Types to be displayed by the Social Timeline
	 * 
	 * This enum is part of the 'sap/collaboration/library' module export and must be accessed by the property 'DisplayFeedType'.
	 *
	 * @public
	*/
	export default DisplayFeedType;
}

declare module "sap/collaboration/FeedType" {
	import {FeedType} from "sap/collaboration/library";

	/**
	 * Feed Types
	 * 
	 * This enum is part of the 'sap/collaboration/library' module export and must be accessed by the property 'FeedType'.
	 *
	 * @public
	*/
	export default FeedType;
}
