name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: General checks, tests and coverage reporting
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 21.4.0
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 21.4.0

    - name: Install dependencies
      run: npm ci

    - name: Perfrom Licenses check
      run: npm run check-licenses

    - name: Perform dependency check
      run: npm run depcheck

    - name: Perform checks and tests
      run: npm test
      env:
        NODE_OPTIONS: ""
