name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: General checks, tests and coverage reporting
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.11.0
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20.11.0

    - name: Install dependencies
      run: npm ci

    - name: Perform ESLint check
      run: npm run lint

    - name: Perform Licenses check
      run: npm run check-licenses

    - name: Perform dependency check
      run: npm run depcheck

    - name: Perform build
      run: npm run build-test

    - name: Run unit tests
      run: npm run coverage

    - name: Send report to Coveralls for package @ui5/linter
      uses: coverallsapp/github-action@v2.3.6
