name: Dependabot auto-merge
on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: If @sapui5/types update, add notice to PR body
        if: ${{contains(steps.metadata.outputs.dependency-names, '@sapui5/types')}}
        run: gh pr edit "$PR_URL" --body "**NOTICE:** This PR informs about a new version of the @sapui5/types package, please manually execute the `npm run update-sapui5-types` script to update the types in the project and amend this commit."
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge for Dependabot PRs (except @sapui5/types)
        if: ${{ contains(fromJSON('["version-update:semver-minor", "version-update:semver-patch"]'), steps.metadata.outputs.update-type) && !contains(steps.metadata.outputs.dependency-names, '@sapui5/types')}}
        run: gh pr review --approve "$PR_URL" && gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
