name: End-To-End Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.11.0
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20.11.0

    - name: Install dependencies
      run: npm ci

    - name: Run e2e tests
      run: npm run e2e
