name: REUSE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compliance-check:
    name: Compliance Check
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Execute REUSE Compliance Check
      uses: fsfe/reuse-action@v5
